services:
  - type: web
    name: expense-ai-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-api-key-here